### ISSUE TITLE
home/index

### ISSUE THREAD

**Issue by thisishailey** [J-P-plan/J-P_APP#8]
## TODO

Search Bar
- [x] UI
- [x] ~~onKeyPress Event~~ onSubmitEditing Event (to search tab)

PlaceCity Sections
- [x] UI
- [x] Link (on More Button click -> list page, on List Item click -> detail page)
- [x] Place API

TravelReview Sections
- [x] UI
- [x] Link (on More Button click -> list page, on List Item click -> detail page)
- [x] Reviews API
- [x] Travel Log API (not available yet, use mock data instead)
